# Generated by Django 6.0.4 on 2026-07-04 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buslistentry',
            constraint=models.UniqueConstraint(fields=('bus_list', 'user'), name='unique_user_per_bus_list'),
        ),
    ]
